import type { Player } from '@/lib/types';

export const players: Player[] = [
  {
    id: 'p1',
    name: 'Jack Murphy',
    number: 2,
    squad: 'cup',
    role: 'leader',
    active: true,
    primaryPosition: 'HB',
    secondaryPosition: 'W',
    runningProfile: 'high',
    rotationGroupOverrides: null,
  },
  {
    id: 'p2',
    name: 'Liam Carter',
    number: 5,
    squad: 'cup',
    role: 'player',
    active: true,
    primaryPosition: 'C',
    secondaryPosition: 'Fol',
    runningProfile: 'balanced',
    rotationGroupOverrides: null,
  },
  {
    id: 'p3',
    name: 'Ben Walsh',
    number: 7,
    squad: 'cup',
    role: 'captain',
    active: true,
    primaryPosition: 'F',
    secondaryPosition: null,
    runningProfile: 'managed',
    rotationGroupOverrides: null,
  },
  {
    id: 'p4',
    name: 'Tom Hayes',
    number: 9,
    squad: 'cup',
    role: 'vice-captain',
    active: true,
    primaryPosition: 'Fol',
    secondaryPosition: 'HF',
    runningProfile: 'balanced',
    rotationGroupOverrides: null,
  },
  {
    id: 'p5',
    name: 'Noah Sullivan',
    number: 11,
    squad: 'plate',
    role: 'player',
    active: true,
    primaryPosition: 'B',
    secondaryPosition: 'HB',
    runningProfile: 'managed',
    rotationGroupOverrides: null,
  },
  {
    id: 'p6',
    name: 'Ethan Brooks',
    number: 14,
    squad: 'plate',
    role: 'player',
    active: true,
    primaryPosition: 'W',
    secondaryPosition: 'HF',
    runningProfile: 'high',
    rotationGroupOverrides: null,
  },
  {
    id: 'p7',
    name: "Sam O'Connor",
    number: 18,
    squad: 'cup',
    role: 'leader',
    active: true,
    primaryPosition: 'HF',
    secondaryPosition: 'C',
    runningProfile: 'high',
    rotationGroupOverrides: null,
  },
  {
    id: 'p8',
    name: 'Cooper Davis',
    number: 21,
    squad: 'plate',
    role: 'player',
    active: true,
    primaryPosition: 'HB',
    secondaryPosition: 'W',
    runningProfile: 'balanced',
    rotationGroupOverrides: null,
  },
  {
    id: 'p9',
    name: 'Harry Quinn',
    number: 24,
    squad: null,
    role: 'player',
    active: true,
    primaryPosition: null,
    secondaryPosition: 'HF',
    runningProfile: 'balanced',
    rotationGroupOverrides: null,
  },
  {
    id: 'p10',
    name: 'Mason Reid',
    number: 27,
    squad: 'plate',
    role: 'player',
    active: false,
    primaryPosition: 'F',
    secondaryPosition: 'HF',
    runningProfile: 'managed',
    rotationGroupOverrides: null,
  },
];
